// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Greeffer

//@version=4
study("Test Azure Functions", "Az Test", overlay=true)
long = input(title="Long (true or false)", type=input.bool, defval=true )

// O R D E R S :
if long==true
    alert(message='{"side":"marketBuy","symbol":"BTCUSDT","amount":"0.001"}', freq=alert.freq_once_per_bar)

if long==false
    alert(message='{"side":"marketSell","symbol":"BTCUSDT","amount":"0.001"}', freq=alert.freq_once_per_bar)
